// Atlas Vivo MILK — Os 16 seres folclóricos oficiais
// Conteúdo curatorial completo da CAMADA_PUBLICA_ENCANTADA.
// Cada ser: nome, natureza, origem, leitura curatorial, charada/convite, dispositivo.

export const SERES = [
  {
    nome: "A Moura Encantada",
    natureza: "Espírito feminino guardião de tesouros, fontes, cavernas e passagens invisíveis. Aparece em noites de São João, penteando cabelos longos com pente de ouro.",
    origem: "Ibérica pré-cristã, com estratificação árabe-islâmica posterior à reconquista. Figura das mouras como almas de donzelas deixadas a guardar o que os mouros levaram. Análoga às nixen germânicas, rusalki russas, vilas sérvias, naiadas gregas.",
    leitura: "A Moura Encantada é o arquétipo de tudo o que está presente e invisível. Não é um fantasma — é um ser real aprisionado por uma força exterior. A sua presença marcou a toponímia de Portugal: Fonte da Moura, Buraco da Moura, Castelo da Moura. Recolher vestígios com o Dado sem Lado é, em muitos casos, tentar quebrar o encanto. Leitura feminista: a moura é descrita como \"perigosamente sedutora\" pelos textos que a documentam — leitura masculina de um ser soberano.",
    charada: "Não me vês de dia, apareço em São João,\nguardo o ouro debaixo da água,\nsó me liberta quem tiver coragem e coração.\nQuem sou eu?",
    resposta: "A Moura Encantada",
    dispositivos: ["galeria-diletante", "dado-sem-lado"],
  },
  {
    nome: "O Lobisomem",
    natureza: "Sétimo filho varão que se transforma em animal nas noites de lua cheia. Em Portugal, raramente se transforma em lobo — em muitos relatos locais, vagueia como homem possuído, rastejando pela terra envergonhado.",
    origem: "Universal com versão ibérica muito própria. Regulado por lógica do pecado hereditário, ausência de batismo e vergonha social. Documentado em Cambra, Vouzela, Trás-os-Montes.",
    leitura: "O lobisomem português não é violento — é uma vítima. Representa o indivíduo que não controla o que lhe acontece ao corpo, que sai à noite contra a vontade, que esconde o que é. Leitura antirracial e queer: o \"feitiço\" que obriga alguém a ser diferente à noite, que exige \"quebrar o segredo para alguém\", que se cura pela confissão. A lenda contém o sofrimento de existir em dois mundos.",
    charada: "Sete irmãos, e eu sou o último.\nDe dia sou como tu, de noite sou outro.\nNão escolhi. Mas quem me nomear com coragem quebra o feitiço.",
    resposta: "O Lobisomem",
    dispositivos: ["dado-sem-lado"],
  },
  {
    nome: "A Coca",
    natureza: "Dragão fêmea, longo e serpenteante, com garras e dentes mortais. Esconde-se em lugares escuros. Rapta crianças. Associada a Monção, onde todos os anos é dramatizada a luta de São Jorge com a Coca.",
    origem: "Mitologia ibérica pré-romana. Variante portuguesa do dragão europeu com marcação feminina. \"Coco\" e \"Coca\" são a mesma figura com intensidades diferentes — uma amedronta à noite, a outra devora.",
    leitura: "A Coca é o monstro que os adultos invocam para controlar crianças. Mas é também o poder feminino bruto que as instituições (São Jorge, a Igreja) precisam de derrotar publicamente, todos os anos, para afirmar ordem. A festa de Monção é um ritual de dominação — e uma celebração do terror sagrado.",
    charada: "Tenho asas que não voam,\ndentes que não comem mesa,\ne todos os anos morro —\ne todos os anos reapareço.",
    resposta: "A Coca",
    dispositivos: ["reizinho", "galeria-diletante"],
  },
  {
    nome: "A Alma Penada",
    natureza: "Espírito de pessoa morta que não pode descansar — por pecado, segredo não dito, injustiça sofrida ou promessa não cumprida. Aparece com luz própria, percorre caminhos nocturnos.",
    origem: "Universal cristã com versão portuguesa muito rica. Documentada em Trás-os-Montes, Minho, Beiras. A alma penada de Goís percorria a serra com candeia, todas as noites, do verão ao inverno.",
    leitura: "As almas penadas são os silêncios da história. São as pessoas que morreram sem que ninguém registasse o nome, sem sepultura digna, sem testemunha. O Dado sem Lado é também uma colecta de almas penadas — tudo o que ficou por dizer, por nomear, por celebrar. O silêncio de uma freguesia no Atlas não significa ausência. Significa que ainda ninguém foi perguntar.",
    charada: "Nem morta nem viva estou,\nando onde andei,\nquem me ouvir fica parado,\nquem me contar fica livre.\nO que sou?",
    resposta: "A Alma Penada",
    dispositivos: ["cronica-fuco", "dado-sem-lado"],
  },
  {
    nome: "O Bicho-Papão / Coco",
    natureza: "Entidade de forma vaga e aterrorizante que existe sobretudo na linguagem dos adultos. Esconde-se debaixo da cama, no armário, no telhado. Existe enquanto a criança acreditar.",
    origem: "Universal. Em Portugal, a forma oral inclui uma canção de ninar: \"Vai-te, Papão, vai-te embora / de cima desse telhado / deixa dormir o menino / um soninho descansado.\"",
    leitura: "O Bicho-Papão é o medo nomeado para poder ser expulso. Dar nome ao medo é o primeiro acto de soberania. A camada pública do Atlas usa esta figura para introduzir o princípio da nomeação — o que não tem nome não pode ser enfrentado nem celebrado.",
    convite: "Conta-nos o teu Bicho-Papão.\nNão o da tua infância — o de agora.\nO que assusta o teu território?",
    dispositivos: ["nuno-vestigios"],
  },
  {
    nome: "O Trasgo",
    natureza: "Duende doméstico travesso. Mexe nos objectos, faz barulhos, assusta mas não mata. Em Trás-os-Montes, associado às almas de crianças que morreram sem baptismo.",
    origem: "Ibérica, com raízes celtas. Equivalente ao brownie escocês, ao kobold alemão, ao domovoi russo. Em Portugal: \"trasgo\", \"duende\", \"fradinho\".",
    leitura: "O Trasgo é a criança não baptizada — a pessoa que o sistema religioso recusou nomear. Historicamente, bebés nascidos mortos, filhos fora do casamento, crianças de mães sem estatuto. A travessura é o que fica quando a presença é negada. Leitura antirracial: a exclusão do nome e do registo como forma de exclusão do ser.",
    charada: "Não me vês mas sabes que estou.\nMovo o que não devia.\nNão sou mau — sou esquecido.\nQual é o meu nome?",
    resposta: "O Trasgo",
    dispositivos: ["dado-sem-lado"],
  },
  {
    nome: "A Moura Encantada Cobra / Serpente",
    natureza: "Variante da Moura que aparece em forma de cobra com cabeleira negra. Documentada especificamente em Figueira de Castelo Rodrigo — a moura que perseguiu o homem que perturbou a sua roupa estendida ao sol.",
    origem: "Ligação entre serpente, mulher e território é uma das mais antigas camadas mitológicas europeias — pré-indo-europeia, pré-cristã.",
    leitura: "A serpente não é o mal — é a guardiã. A transformação é a consequência da violação de um limite territorial. Cada freguesia tem os seus limites invisíveis.",
    dispositivos: ["galeria-diletante", "dado-sem-lado"],
  },
  {
    nome: "O Gambozino",
    natureza: "Animal que não existe, mas que as pessoas procuram com convicção. É pequeno, peludo e extraordinariamente difícil de apanhar. As crianças novas são enviadas a apanhá-lo com uma caixinha e sal.",
    origem: "Portuguesa. Ritual de iniciação e brincadeira intergeracional. O gambozino é o pretexto perfeito para ocupar alguém.",
    leitura: "O Gambozino é a melhor figura para descrever o Dado sem Lado. Existe — acreditamos que existe — mas o vestígio é sempre esquivo. A recolha é sempre incompleta. O Atlas aceita isso.",
    convite: "Já foste à caça do gambozino?\nConta-nos onde foi, como foi, quem te mandou.",
    dispositivos: ["nuno-vestigios", "reizinho"],
  },
  {
    nome: "A Mulher Marinha",
    natureza: "Ser híbrido — metade mulher, metade criatura marinha. Pés de cabra, escamas, orelhas grandes. Saía do mar e casava com homens da terra, trazendo fertilidade e fortuna.",
    origem: "Portuguesa e atlântica, com analogias nas selkies escocesas, nas Faroé e na Islândia. Ligada à presença de focas nas costas portuguesas. Nos Açores, é uma entidade de transformação e fortuna.",
    leitura: "A Mulher Marinha é a estrangeira que se integra e enriquece o território. A \"outra\" que traz o que falta. Leitura feminista: o seu valor é medido pelo que dá ao homem. O Atlas lê-a diferente — ela é soberana do mar, que vem por escolha e parte por escolha.",
    charada: "Sou de dois mundos e de nenhum.\nQuando me vês, já me perdi.\nO que ganhas quando chego,\nperdes quando parto.\nQuem sou?",
    resposta: "A Mulher Marinha",
    dispositivos: ["galeria-diletante"],
  },
  {
    nome: "O Fradinho da Mão Furada",
    natureza: "Duende travesso e doméstico, com uma mão furada por onde escorregam as moedas. Muito popular no Alentejo e Algarve. Associado à sorte e ao esconderijo de tesouros.",
    origem: "Portuguesa. A mão furada é o símbolo do que não se segura — a riqueza que não se acumula, que passa.",
    leitura: "O Fradinho é a figura da redistribuição involuntária. A riqueza que não fica. Leitura económica: territórios de baixa densidade onde o capital sai mais depressa do que entra — o Fradinho como metáfora viva de desequilíbrios territoriais.",
    travaLingua: "O fradinho da mão furada\nfurou a mão, furou a frada,\nfurou o furo da furada\ne fugiu com a moeda furada.",
    dispositivos: ["reizinho", "dado-sem-lado"],
  },
  {
    nome: "O João Pestana",
    natureza: "O ser que traz o sono. Chega quando a criança está quase a adormecer e pousa pó de sonho nos olhos.",
    origem: "Equivalente português do Sandman europeu. Figura universal de adormecimento.",
    leitura: "João Pestana é a figura do arquivo. Guarda os sonhos que não foram vividos acordado — os desejos não ditos, as memórias que só existem na fronteira do sono. A recolha do Dado sem Lado inclui esta fronteira.",
    convite: "João Pestana veio já,\nde que cor foi o teu sonho hoje?\nConta antes de acordar completamente.",
    dispositivos: ["cronica-fuco"],
  },
  {
    nome: "O Tardo / Pesadelo",
    natureza: "Duende que se senta sobre o peito das pessoas adormecidas e lhes rouba o ar. Se alguém conseguir tirar o seu carapuço, ele é obrigado a dar todo o dinheiro que lhe for pedido.",
    origem: "Portuguesa. Uma criança pode tornar-se um Tardo se o padrinho não disser as palavras certas no baptismo. Depois de 7 anos sem quebrar o fado, transforma-se em lobisomem.",
    leitura: "O Tardo é a ansiedade nocturna com corpo. O peso no peito. Leitura de saúde mental: muitos dos seres do folclore português dão forma e nome a experiências corporais que não tinham outro vocabulário.",
    charada: "Não me vês mas sentes o meu peso.\nNão sou mau — sou o que não disseste.\nQuem me nomear adormece em paz.",
    resposta: "O Tardo",
    dispositivos: ["dado-sem-lado"],
  },
  {
    nome: "A Santa Companha",
    natureza: "Procissão de fantasmas que percorre os caminhos nocturnos, anunciando morte. Quem a vê pode ser obrigado a carregar a cruz e juntar-se ao cortejo. Para escapar, há que deitar um círculo no chão e ficar dentro.",
    origem: "Galego-portuguesa. Compaña na Galiza, Hueste nas Astúrias, Ankou na Bretanha. Documentada em todo o noroeste peninsular.",
    leitura: "A Santa Companha é o arquivo dos mortos que caminham. É a memória colectiva em movimento — quem não é lembrado junta-se ao cortejo. O Atlas Vivo MILK é, em parte, uma forma de impedir que certas pessoas, saberes e práticas se juntem à procissão.",
    convite: "Conheces alguém que a Santa Companha levou antes de tempo?\nDeixa o nome aqui. Que fique.",
    dispositivos: ["cronica-fuco"],
  },
  {
    nome: "Pedro Malasartes",
    natureza: "Burlão invencível, astucioso, sem escrúpulos, que sempre leva a melhor dos poderosos. Primeira menção no Cancioneiro da Vaticana, séculos XIII-XIV. Figura de resistência popular.",
    origem: "Portuguesa e ibérica. Equivalentes: Pedro Urdemales (Castela), Till Eulenspiegel (Alemanha). No Brasil, gerou João Grilo, Amigo-da-Onça, Zé Carioca.",
    leitura: "Pedro Malasartes é o arquivo vivo da resistência. Em todas as culturas onde há grandes diferenças sociais, o pobre esperto engana o rico tolo. O Atlas recolhe estas histórias como dados de desigualdade — mais honestos do que qualquer estatística.",
    charada: "Sou pobre, sou esperto, sou livre.\nEnganei o rei, o padre e o rico.\nNão sou herói — sou o que sobrou.\nQuem sou eu?",
    resposta: "Pedro Malasartes",
    dispositivos: ["galeria-diletante", "reizinho"],
  },
  {
    nome: "O Insonho",
    natureza: "Espírito ou bruxa que perturba o sono. Tem um carapuço especial — quem lho tirar obriga-o a dar todo o dinheiro que lhe pedirem até recuperar o carapuço.",
    origem: "Portuguesa. Variante do duende/espírito noturno com mecânica de negociação e poder.",
    leitura: "O Insonho é a figura da negociação impossível — o ser que tem poder mas pode ser dobrado por quem conhece a regra. Leitura de dados: o poder dos dados é que quem os tem pode ser obrigado a distribuí-los, se alguém souber como pedir.",
    dispositivos: ["dado-sem-lado"],
  },
  {
    nome: "O Reizinho que não tinha rainha",
    natureza: "Figura editorial original do Atlas Vivo MILK. Rei sem rainha porque ele mesmo usava sainha. Personagem criado no âmbito da curadoria interna como figura de dissidência de género no folclore português.",
    origem: "Tradição oral de resistência popular; figuras de inversão de género presentes em múltiplos registos europeus (o rei que veste de mulher no carnaval, o \"Dia dos Rapazes\" em Trás-os-Montes onde os jovens invertem papéis sociais).",
    leitura: "O Reizinho é a prova de que o folclore sempre soube o que as instituições tardaram séculos a admitir. A dissidência de género não é uma importação contemporânea — é uma tradição oral antiga, mascarada de carnaval ou de fantasia, que circulou nas aldeias durante séculos.",
    dispositivos: ["reizinho", "galeria-diletante"],
  },
];
